# repository_dispatch api triggered workflow
# event_type "Triggered Workflow"
# to do 
# steps
# checkout csms seed branch of interest
# regenrate the labels
# push if the labels if changed

name: generate script

on:
    push:
        branches:
              - feature/test

jobs:
    generate:
     name: generate seed
     runs-on: ubuntu-latest

     steps:
        - name: cdgc-ui-common
          uses: actions/checkout@v3
          with:
            path: ui-common

        - name: checkout repo
          uses: actions/checkout@v3
          with:
            repository: poornendushukla/realTimeTable
            token: ${{secrets.ACTION_KEY}}    
            path: otherRepo

        - name: setup repo path
          run: |
           echo "REPO_PATH=$(pwd)/otherRepo" >> "$GITHUB_ENV"

        - name: setup node
          uses: actions/setup-node@v3
          with:
            node-version: 14

        - name: Installing packages in ui-common 
          run: |
            echo "installing packages"
            echo "dev_user_name=$GTIHUB_PATH" >> "$GITHUB_ENV"
            cd main
            npm ci
            rm -rf node_modules
            echo "${{env.REPO_PATH}}"

        # - name: capture actor
        #   run: |
        #     echo "dev_user_name=${{ github.actor }}" >> "$GITHUB_ENV"
        #     node -e "console.log('dev_user_email=', '${{ github.actor }}'.split('_')[0] + '@informatica.com')" >> "$GITHUB_ENV"\
          
        # - name: push generated translations 
        #   run: |
        #     git pull origin
        #     git status
        #     git add --all
        #     git commit -a -m "auto generated seed translations" || echo ""
        #     git push
        #   env:
        #     GIT_AUTHOR_NAME: ${{ env.dev_user_name }}
        #     GIT_AUTHOR_EMAIL: ${{ env.dev_user_email }}
        #     GIT_COMMITTER_NAME: ${{ env.dev_user_name }}
        #     GIT_COMMITTER_EMAIL: ${{ env.dev_user_email }}
         



        


