# repository_dispatch api triggered workflow
# event_type "Triggered Workflow"
# to do 
# steps
# checkout csms seed branch of interest
# regenrate the labels
# push if the labels if changed

name: generate script

on:
    push:
        branches:
              - main

jobs:
    generate:
     name: generate seed
     runs-on: ubuntu-latest

     steps:
        - name: cdgc-ui-common
          uses: actions/checkout@v3
          with:
            path: main

        - name: checkout repo
          uses: actions/checkout@v3
          with:
            repository: poornendushukla/realTimeTable
            token: ${{secrets.GITHUB_TOKEN}}    
            path: otherRepo

        - name: setup node
          uses: actions/setup-node@v3
          with:
            node-version: 14


        - name: chekcout multiple branches
          run: |
            echo "ROOT"
            ls -la
            echo "cdgc-ui-common"
            cd main
            ls -la
            cd ..
            echo "otherRepo"
            cd otherRepo
            ls -la
        - name: Installing packages in ui-common 
          run: |
            echo "installing packages"
            cd main
            npm ci
            echo __dirname



        


